[tool.poetry]
name = "s3-account-search"
version = "0.2.1"
description = "Search for the AWS Account that contains an S3 bucket or object"
authors = ["Ben Bridts"]

[tool.poetry.dependencies]
python = "^3.11"
boto3 = "^1.16.49"
aws-assume-role-lib = "^2.10.0"
six = "^1.17.0"
pytest = "^9.0.3"
[tool.poetry.dev-dependencies]

[tool.poetry.scripts]
s3-account-finder = 's3_account_search.cli:run'
s3-account-search = 's3_account_search.cli:run'

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
